export const POSTS = [
  { label: 'Директор', value: 'director' },
  { label: 'Учитель', value: 'teacher' },
  { label: 'Родитель', value: 'parent' },
];
export const CITIES = [
  { label: 'Балахна', value: 'blagoveshchensk' },
  { label: 'Благовещенск (Дальний Восток)', value: 'blagoveshchensk-dv' },
  { label: 'Благовещенск (Республика Башкортостан)', value: 'blagoveshchensk-bashk' },
  { label: 'Воронеж', value: 'voronezh' },
  { label: 'Дзержинск', value: 'dzerzhinsk' },
  { label: 'Казань', value: 'kazan' },
  { label: 'Красноярск', value: 'krasnoyarsk' },
  { label: 'Кстово', value: 'kstovo' },
  { label: 'Москва и МО', value: 'moskva-i-mo' },
  { label: 'Нижневартовск', value: 'nizhnevartovsk' },
  { label: 'Нижнекамск', value: 'nizhnekamsk' },
  { label: 'Нижний Новгород', value: 'n-novgorod' },
  { label: 'Новокуйбышевск', value: 'novokujbyshevsk' },
  { label: 'Ноябрьск', value: 'noyabrsk' },
  { label: 'Нягань', value: 'nyagan' },
  { label: 'Пермь', value: 'perm' },
  { label: 'Пыть-Ях', value: 'pyt-yah' },
  { label: 'Свободный', value: 'svobodnyj' },
  { label: 'Тверь', value: 'tver' },
  { label: 'Тобольск', value: 'tobolsk' },
  { label: 'Томск', value: 'tomsk' },
  { label: 'Тюмень', value: 'tyumen' },
  { label: 'Усть-Лужское с/п', value: 'ust-luzhskoe' },
  { label: 'Уфа', value: 'ufa' },
];